// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package catalogdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

type Product struct {
	ID          int32            `json:"id"`
	Uuid        pgtype.UUID      `json:"uuid"`
	Title       string           `json:"title"`
	Price       pgtype.Numeric   `json:"price"`
	Quality     int32            `json:"quality"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Description *string          `json:"description"`
	IsPublished bool             `json:"is_published"`
	IsDeleted   bool             `json:"is_deleted"`
	Slug        *string          `json:"slug"`
	CategoryID  *int32           `json:"category_id"`
}
