// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM product
WHERE is_deleted = false
  AND ($1::int  IS NULL OR category_id  = $1)
  AND ($2::bool   IS NULL OR is_published = $2)
  AND ($3::text      IS NULL OR title ILIKE '%' || $3 || '%')
`

type CountProductsParams struct {
	CategoryID *int32  `json:"category_id"`
	Published  *bool   `json:"published"`
	Search     *string `json:"search"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.CategoryID, arg.Published, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductByUUID = `-- name: GetProductByUUID :one
SELECT
    id,
    uuid::text  AS uuid,
    title,
    price::text AS price,
    quality,
    description,
    is_published,
    slug,
    category_id
FROM product
WHERE uuid = $1 AND is_deleted = false
`

type GetProductByUUIDRow struct {
	ID          int32   `json:"id"`
	Uuid        string  `json:"uuid"`
	Title       string  `json:"title"`
	Price       string  `json:"price"`
	Quality     int32   `json:"quality"`
	Description *string `json:"description"`
	IsPublished bool    `json:"is_published"`
	Slug        *string `json:"slug"`
	CategoryID  *int32  `json:"category_id"`
}

func (q *Queries) GetProductByUUID(ctx context.Context, productUuid pgtype.UUID) (GetProductByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByUUID, productUuid)
	var i GetProductByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Price,
		&i.Quality,
		&i.Description,
		&i.IsPublished,
		&i.Slug,
		&i.CategoryID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, title, slug
FROM category
ORDER BY title
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Title, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    uuid::text  AS uuid,
    title,
    price::text AS price,
    quality,
    description,
    is_published,
    slug,
    category_id
FROM product
WHERE is_deleted = false
  AND ($1::int  IS NULL OR category_id  = $1)
  AND ($2::bool   IS NULL OR is_published = $2)
  AND ($3::text      IS NULL OR title ILIKE '%' || $3 || '%')
ORDER BY id DESC
LIMIT $5 OFFSET $4
`

type ListProductsParams struct {
	CategoryID *int32  `json:"category_id"`
	Published  *bool   `json:"published"`
	Search     *string `json:"search"`
	Off        int32   `json:"off"`
	Lim        int32   `json:"lim"`
}

type ListProductsRow struct {
	ID          int32   `json:"id"`
	Uuid        string  `json:"uuid"`
	Title       string  `json:"title"`
	Price       string  `json:"price"`
	Quality     int32   `json:"quality"`
	Description *string `json:"description"`
	IsPublished bool    `json:"is_published"`
	Slug        *string `json:"slug"`
	CategoryID  *int32  `json:"category_id"`
}

// uuid/price приводим к text: pgtype-обёртки наружу не нужны, домен оперирует строками.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID,
		arg.Published,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Price,
			&i.Quality,
			&i.Description,
			&i.IsPublished,
			&i.Slug,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
