// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package orderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

type CheckoutIdempotency struct {
	Key       string             `json:"key"`
	SessionID string             `json:"session_id"`
	OrderID   int32              `json:"order_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID         int32            `json:"id"`
	OwnerID    *int32           `json:"owner_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	Status     int32            `json:"status"`
	TotalPrice *float64         `json:"total_price"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	IsDeleted  bool             `json:"is_deleted"`
}

type OrderProduct struct {
	ID          int32          `json:"id"`
	AppOrderID  int32          `json:"app_order_id"`
	ProductID   int32          `json:"product_id"`
	Quantity    int32          `json:"quantity"`
	PricePerOne pgtype.Numeric `json:"price_per_one"`
}

type Outbox struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Traceparent   *string            `json:"traceparent"`
}

type Product struct {
	ID          int32            `json:"id"`
	Uuid        pgtype.UUID      `json:"uuid"`
	Title       string           `json:"title"`
	Price       pgtype.Numeric   `json:"price"`
	Quality     int32            `json:"quality"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Description *string          `json:"description"`
	IsPublished bool             `json:"is_published"`
	IsDeleted   bool             `json:"is_deleted"`
	Slug        *string          `json:"slug"`
	CategoryID  *int32           `json:"category_id"`
	Stock       int32            `json:"stock"`
}
