// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package orderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT count(*)
FROM "order"
WHERE is_deleted = false
  AND ($1::int IS NULL OR owner_id = $1)
  AND ($2::int   IS NULL OR status   = $2)
`

type CountOrdersParams struct {
	OwnerID *int32 `json:"owner_id"`
	Status  *int32 `json:"status"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.OwnerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrder = `-- name: GetOrder :one
SELECT
    id,
    owner_id,
    status,
    coalesce(total_price, 0)::numeric(10, 2)::text AS total,
    created_at,
    updated_at
FROM "order"
WHERE id = $1 AND is_deleted = false
`

type GetOrderRow struct {
	ID        int32            `json:"id"`
	OwnerID   *int32           `json:"owner_id"`
	Status    int32            `json:"status"`
	Total     string           `json:"total"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetOrder(ctx context.Context, id int32) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO checkout_idempotency (key, session_id, order_id)
VALUES ($1, $2, $3)
`

type InsertIdempotencyKeyParams struct {
	Key       string `json:"key"`
	SessionID string `json:"session_id"`
	OrderID   int32  `json:"order_id"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.SessionID, arg.OrderID)
	return err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO "order" (id, owner_id, created_at, status, total_price, updated_at, is_deleted)
VALUES (
    nextval('"order_id_seq"'),
    $1,
    now(),
    $2,
    $3,
    now(),
    false
)
RETURNING id, created_at, updated_at
`

type InsertOrderParams struct {
	OwnerID    *int32   `json:"owner_id"`
	Status     int32    `json:"status"`
	TotalPrice *float64 `json:"total_price"`
}

type InsertOrderRow struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// id берём из doctrine-последовательности: таблицу делим с PHP, свои id заводить нельзя.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (InsertOrderRow, error) {
	row := q.db.QueryRow(ctx, insertOrder, arg.OwnerID, arg.Status, arg.TotalPrice)
	var i InsertOrderRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertOrderProduct = `-- name: InsertOrderProduct :exec
INSERT INTO order_product (id, app_order_id, product_id, quantity, price_per_one)
VALUES (
    nextval('order_product_id_seq'),
    $1,
    $2,
    $3,
    $4
)
`

type InsertOrderProductParams struct {
	AppOrderID  int32          `json:"app_order_id"`
	ProductID   int32          `json:"product_id"`
	Quantity    int32          `json:"quantity"`
	PricePerOne pgtype.Numeric `json:"price_per_one"`
}

func (q *Queries) InsertOrderProduct(ctx context.Context, arg InsertOrderProductParams) error {
	_, err := q.db.Exec(ctx, insertOrderProduct,
		arg.AppOrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PricePerOne,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (aggregate_type, aggregate_id, event_type, payload)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertOutboxEventParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	EventType     string `json:"event_type"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT
    op.product_id,
    p.uuid::text            AS uuid,
    p.title,
    op.price_per_one::text  AS price_per_one,
    op.quantity
FROM order_product op
JOIN product p ON p.id = op.product_id
WHERE op.app_order_id = $1
ORDER BY op.id
`

type ListOrderItemsRow struct {
	ProductID   int32  `json:"product_id"`
	Uuid        string `json:"uuid"`
	Title       string `json:"title"`
	PricePerOne string `json:"price_per_one"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) ListOrderItems(ctx context.Context, appOrderID int32) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, appOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Uuid,
			&i.Title,
			&i.PricePerOne,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
    id,
    owner_id,
    status,
    coalesce(total_price, 0)::numeric(10, 2)::text AS total,
    created_at,
    updated_at
FROM "order"
WHERE is_deleted = false
  AND ($1::int IS NULL OR owner_id = $1)
  AND ($2::int   IS NULL OR status   = $2)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListOrdersParams struct {
	OwnerID *int32 `json:"owner_id"`
	Status  *int32 `json:"status"`
	Off     int32  `json:"off"`
	Lim     int32  `json:"lim"`
}

type ListOrdersRow struct {
	ID        int32            `json:"id"`
	OwnerID   *int32           `json:"owner_id"`
	Status    int32            `json:"status"`
	Total     string           `json:"total"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.OwnerID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderStatus = `-- name: LockOrderStatus :one
SELECT status FROM "order" WHERE id = $1 AND is_deleted = false FOR UPDATE
`

func (q *Queries) LockOrderStatus(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockOrderStatus, id)
	var status int32
	err := row.Scan(&status)
	return status, err
}

const lockProductsForCheckout = `-- name: LockProductsForCheckout :many
SELECT
    id,
    uuid::text  AS uuid,
    title,
    price::text AS price,
    stock
FROM product
WHERE uuid = ANY($1::uuid[])
  AND is_deleted = false
ORDER BY id
FOR UPDATE
`

type LockProductsForCheckoutRow struct {
	ID    int32  `json:"id"`
	Uuid  string `json:"uuid"`
	Title string `json:"title"`
	Price string `json:"price"`
	Stock int32  `json:"stock"`
}

// ORDER BY id до FOR UPDATE: LockRows стоит над сортировкой, поэтому строки
// блокируются в одном и том же порядке во всех параллельных checkout-ах — без этого
// две корзины с пересекающимся составом ловят дедлок.
func (q *Queries) LockProductsForCheckout(ctx context.Context, uuids []pgtype.UUID) ([]LockProductsForCheckoutRow, error) {
	rows, err := q.db.Query(ctx, lockProductsForCheckout, uuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockProductsForCheckoutRow
	for rows.Next() {
		var i LockProductsForCheckoutRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderIDByIdempotencyKey = `-- name: OrderIDByIdempotencyKey :one
SELECT order_id FROM checkout_idempotency WHERE key = $1
`

func (q *Queries) OrderIDByIdempotencyKey(ctx context.Context, key string) (int32, error) {
	row := q.db.QueryRow(ctx, orderIDByIdempotencyKey, key)
	var order_id int32
	err := row.Scan(&order_id)
	return order_id, err
}

const reserveStock = `-- name: ReserveStock :exec
UPDATE product SET stock = stock - $1 WHERE id = $2
`

type ReserveStockParams struct {
	Qty int32 `json:"qty"`
	ID  int32 `json:"id"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) error {
	_, err := q.db.Exec(ctx, reserveStock, arg.Qty, arg.ID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE "order" SET status = $1, updated_at = now() WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status int32 `json:"status"`
	ID     int32 `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
